package com.ecommerce.product;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.ecommerce.media.ProductMediaStorageService;
import com.ecommerce.media.StoreMediaRepository;
import com.ecommerce.tag.StoreTagService;
import com.ecommerce.tag.TagRepository;
import java.math.BigDecimal;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.transaction.support.TransactionSynchronizationUtils;
import org.springframework.web.server.ResponseStatusException;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

/**
 * Isolated persistence tests for {@link StoreProductService} against embedded H2.
 * The {@code spring.config.import=} override disables the optional {@code .env}
 * file so the test never picks up the developer's MySQL datasource.
 */
@DataJpaTest(
        properties = {
            "spring.config.import=",
            "spring.datasource.url=jdbc:h2:mem:products;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false",
            "spring.datasource.driver-class-name=org.h2.Driver",
            "spring.datasource.username=sa",
            "spring.datasource.password="
        })
class StoreProductServiceTest {
    private static final String STORE = "store-1";
    private static final String ORG = "org-1";
    private static final String OWNER = "owner-1";
    private static final BigDecimal TEN = new BigDecimal("10.00");

    @Autowired private ProductRepository productRepository;
    @Autowired private ProductRedirectRepository redirectRepository;
    @Autowired private TagRepository tagRepository;
    @Autowired private StoreMediaRepository storeMediaRepository;

    private StoreProductService service;
    private ProductMediaStorageService storageService;

    @BeforeEach
    void setUp() {
        storageService = mock(ProductMediaStorageService.class);
        service = new StoreProductService(
                productRepository,
                redirectRepository,
                new StoreTagService(tagRepository),
                storageService,
                storeMediaRepository);
    }

    /** Build a minimal ProductRequest; only the columns exercised by tests are set. */
    private ProductRequest req(
            String title,
            BigDecimal price,
            String sku,
            String barcode,
            String category,
            String categoryPath,
            String categoryPublicId,
            String slug,
            Boolean createRedirect) {
        return new ProductRequest(
                title, slug, null, null, null, null,
                category, categoryPath, categoryPublicId, null,
                price, null, null, sku, barcode,
                null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                createRedirect, List.of(), List.of(), List.of(), List.of());
    }

    private ProductRequest reqWithImages(String title, List<ProductImageRequest> images) {
        return new ProductRequest(
                title, null, null, null, null, null,
                null, null, null, null,
                TEN, null, null, null, null,
                null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                null, List.of(), images, List.of(), List.of());
    }

    @Test
    void titleIsRequired() {
        assertThatThrownBy(() -> service.create(STORE, OWNER, req(null, TEN, null, null, null, null, null, null, null)))
                .isInstanceOf(ResponseStatusException.class)
                .hasMessageContaining("title");
    }

    @Test
    void priceIsRequired() {
        assertThatThrownBy(() -> service.create(STORE, OWNER, req("Tee", null, null, null, null, null, null, null, null)))
                .isInstanceOf(ResponseStatusException.class)
                .hasMessageContaining("price");
    }

    @Test
    void negativePriceRejected() {
        assertThatThrownBy(() ->
                        service.create(STORE, OWNER, req("Tee", new BigDecimal("-1"), null, null, null, null, null, null, null)))
                .isInstanceOf(ResponseStatusException.class)
                .hasMessageContaining("price");
    }

    @Test
    void skuAndBarcodeAutoGeneratedWhenBlank() {
        ProductData data = service.create(STORE, OWNER, req("Tee", new BigDecimal("499"), null, null, null, null, null, null, null));
        assertThat(data.sku()).startsWith("SKU-");
        assertThat(data.barcode()).hasSize(13);
        assertThat(data.barcode()).matches("\\d{13}");
    }

    @Test
    void explicitSkuIsKept() {
        ProductData data = service.create(STORE, OWNER, req("Tee", TEN, "MY-SKU-1", null, null, null, null, null, null));
        assertThat(data.sku()).isEqualTo("MY-SKU-1");
    }

    @Test
    void duplicateSkuOnCreateRejected() {
        service.create(STORE, OWNER, req("A", TEN, "DUP", null, null, null, null, null, null));
        assertThatThrownBy(() -> service.create(STORE, OWNER, req("B", TEN, "DUP", null, null, null, null, null, null)))
                .isInstanceOf(ResponseStatusException.class)
                .hasMessageContaining("already used");
    }

    @Test
    void updateKeepingOwnSkuIsAllowed() {
        ProductData created = service.create(STORE, OWNER, req("A", TEN, "OWN", null, null, null, null, null, null));
        ProductData updated =
                service.update(
                        STORE,
                        ORG,
                        created.publicProductId(),
                        req("A renamed", TEN, "OWN", null, null, null, null, null, null));
        assertThat(updated.sku()).isEqualTo("OWN");
        assertThat(updated.title()).isEqualTo("A renamed");
    }

    @Test
    void updateToAnotherProductsSkuRejected() {
        service.create(STORE, OWNER, req("A", TEN, "AAA", null, null, null, null, null, null));
        ProductData b = service.create(STORE, OWNER, req("B", TEN, "BBB", null, null, null, null, null, null));
        assertThatThrownBy(() ->
                        service.update(
                                STORE,
                                ORG,
                                b.publicProductId(),
                                req("B", TEN, "AAA", null, null, null, null, null, null)))
                .isInstanceOf(ResponseStatusException.class)
                .hasMessageContaining("already used");
    }

    @Test
    void skuUniquenessIsScopedPerStore() {
        service.create(STORE, OWNER, req("A", TEN, "SHARED", null, null, null, null, null, null));
        ProductData other = service.create("store-2", OWNER, req("B", TEN, "SHARED", null, null, null, null, null, null));
        assertThat(other.sku()).isEqualTo("SHARED");
    }

    @Test
    void categoryContextIsStored() {
        ProductData data = service.create(
                STORE, OWNER, req("Kurta", TEN, null, null, "Kurtas", "Ethnic Wear > Kurtas", "cat-123", null, null));
        assertThat(data.category()).isEqualTo("Kurtas");
        assertThat(data.categoryPath()).isEqualTo("Ethnic Wear > Kurtas");
        assertThat(data.categoryPublicId()).isEqualTo("cat-123");
    }

    @Test
    void slugRedirectRecordedWhenSlugChangesAndFlagSet() {
        ProductData created = service.create(STORE, OWNER, req("Kurta", TEN, null, null, null, null, null, "old-slug", null));
        service.update(
                STORE,
                ORG,
                created.publicProductId(),
                req("Kurta", TEN, null, null, null, null, null, "new-slug", true));

        List<ProductRedirectData> redirects = service.redirects(STORE);
        assertThat(redirects).hasSize(1);
        assertThat(redirects.get(0).fromSlug()).isEqualTo("old-slug");
        assertThat(redirects.get(0).toSlug()).isEqualTo("new-slug");
        assertThat(redirects.get(0).publicProductId()).isEqualTo(created.publicProductId());
    }

    @Test
    void noRedirectWhenFlagNotSet() {
        ProductData created = service.create(STORE, OWNER, req("Kurta", TEN, null, null, null, null, null, "old-slug", null));
        service.update(
                STORE,
                ORG,
                created.publicProductId(),
                req("Kurta", TEN, null, null, null, null, null, "new-slug", false));
        assertThat(service.redirects(STORE)).isEmpty();
    }

    @Test
    void updateDeletesRemovedCloudImages() {
        String oldUrl = "https://storage.googleapis.com/shy-pub/store-1/old.jpg";
        String keptUrl = "https://storage.googleapis.com/shy-pub/store-1/kept.jpg";
        ProductData created = service.create(
                STORE,
                OWNER,
                reqWithImages("Kurta", List.of(
                        new ProductImageRequest(oldUrl, null, 0, true),
                        new ProductImageRequest(keptUrl, null, 1, false))));

        service.update(
                STORE,
                ORG,
                created.publicProductId(),
                reqWithImages("Kurta", List.of(new ProductImageRequest(keptUrl, null, 0, true))));

        TransactionSynchronizationUtils.triggerAfterCommit();
        verify(storageService).deleteProductImagesAsync(STORE, ORG, Set.of(oldUrl));
    }

    @Test
    void deleteProductDeletesCloudImages() {
        String imageUrl = "https://storage.googleapis.com/shy-pub/store-1/product.jpg";
        ProductData created = service.create(
                STORE,
                OWNER,
                reqWithImages("Kurta", List.of(new ProductImageRequest(imageUrl, null, 0, true))));

        service.delete(STORE, ORG, created.publicProductId());

        TransactionSynchronizationUtils.triggerAfterCommit();
        verify(storageService).deleteProductImagesAsync(STORE, ORG, Set.of(imageUrl));
    }
}
